

package course;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"LoyaltyNumberConstraint",
			"AttributeConstraint",
			com.epam.course.jalo.LoyaltyNumberConstraint.class,
			null,
			false,
			null,
			false
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_Customer_loyaltyCardNumber();
			
				single_createattr_Customer_marketingComments();
			
				single_createattr_LoyaltyNumberConstraint_annotation();
			

	}

	
	public void single_createattr_Customer_loyaltyCardNumber() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Customer", 
					"loyaltyCardNumber",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Customer_marketingComments() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = new HashMap();
						
							sqlColumnDefinitions.put(
								"oracle",
								"CLOB"
							);
						
							sqlColumnDefinitions.put(
								"sap",
								"NCLOB"
							);
						
							sqlColumnDefinitions.put(
								de.hybris.platform.persistence.property.PersistenceManager.NO_DATABASE,
								"HYBRIS.LONG_STRING"
							);
						
				createPropertyAttribute(
					"Customer", 
					"marketingComments",  
					null,
					"localized:java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_LoyaltyNumberConstraint_annotation() throws JaloBusinessException
	{
		
				redeclareAttribute(
					"LoyaltyNumberConstraint", 
					"annotation",
					"java.lang.Class",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.INITIAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
				{
				Map customPropsMap = new HashMap();
				
				changeMetaType(
					"Customer",
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_Customer_loyaltyCardNumber();
		
			single_setAttributeProperties_Customer_marketingComments();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"LoyaltyNumberConstraint",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_LoyaltyNumberConstraint_annotation();
		
	}


		
						public void single_setAttributeProperties_Customer_loyaltyCardNumber() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Customer", 
								"loyaltyCardNumber",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Customer_marketingComments() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Customer", 
								"marketingComments",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_LoyaltyNumberConstraint_annotation() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"LoyaltyNumberConstraint", 
								"annotation",
								false, 
								com.epam.course.constraints.LoyaltyCardNumber.class,
								"com.epam.course.constraints.LoyaltyCardNumber.class",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
}

	